config/routes.rb
Rails.application.routes.draw do
  resources :products
  get 'pages/products'
  resources :names
  get 'pages/home'
  get 'pages/about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/name.rb
class Name < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/names_controller.rb
class NamesController < ApplicationController
  before_action :set_name, only: [:show, :edit, :update, :destroy]

  # GET /names
  # GET /names.json
  def index
    @names = Name.all
  end

  # GET /names/1
  # GET /names/1.json
  def show
  end

  # GET /names/new
  def new
    @name = Name.new
  end

  # GET /names/1/edit
  def edit
  end

  # POST /names
  # POST /names.json
  def create
    @name = Name.new(name_params)

    respond_to do |format|
      if @name.save
        format.html { redirect_to @name, notice: 'Name was successfully created.' }
        format.json { render :show, status: :created, location: @name }
      else
        format.html { render :new }
        format.json { render json: @name.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /names/1
  # PATCH/PUT /names/1.json
  def update
    respond_to do |format|
      if @name.update(name_params)
        format.html { redirect_to @name, notice: 'Name was successfully updated.' }
        format.json { render :show, status: :ok, location: @name }
      else
        format.html { render :edit }
        format.json { render json: @name.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /names/1
  # DELETE /names/1.json
  def destroy
    @name.destroy
    respond_to do |format|
      format.html { redirect_to names_url, notice: 'Name was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_name
      @name = Name.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def name_params
      params.require(:name).permit(:price)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def products
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/names_helper.rb
module NamesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link active" href="<%= pages_home_path%>">Home <span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link" href="<%= pages_about_path%>">About</a>
      <a class="nav-item nav-link" href="<%=products_path%>">Product</a>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Actividad24</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar'%>"
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/names/_form.html.erb
<%= form_with(model: name, local: true) do |form| %>
  <% if name.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(name.errors.count, "error") %> prohibited this name from being saved:</h2>

      <ul>
      <% name.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/names/edit.html.erb
<h1>Editing Name</h1>

<%= render 'form', name: @name %>

<%= link_to 'Show', @name %> |
<%= link_to 'Back', names_path %>

app/views/names/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Names</h1>

<table>
  <thead>
    <tr>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @names.each do |name| %>
      <tr>
        <td><%= name.price %></td>
        <td><%= link_to 'Show', name %></td>
        <td><%= link_to 'Edit', edit_name_path(name) %></td>
        <td><%= link_to 'Destroy', name, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Name', new_name_path %>

app/views/names/new.html.erb
<h1>New Name</h1>

<%= render 'form', name: @name %>

<%= link_to 'Back', names_path %>

app/views/names/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Price:</strong>
  <%= @name.price %>
</p>

<%= link_to 'Edit', edit_name_path(@name) %> |
<%= link_to 'Back', names_path %>

app/views/pages/about.html.erb
<div class="row">
  <h1>Pages#about</h1>
  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce a lacus vitae lacus ornare sollicitudin a ut turpis. Nam id diam ut velit hendrerit vestibulum rhoncus vitae risus. Suspendisse feugiat mollis velit, non molestie sem viverra sed. Sed at ipsum at felis porttitor consequat eget at arcu. Duis bibendum nunc nec elit condimentum, a tincidunt nulla viverra. Maecenas eget nulla at massa faucibus accumsan. Duis pretium ipsum vel volutpat facilisis. Duis ornare pharetra orci et ullamcorper. Suspendisse lacinia augue dolor, eu rutrum ante fringilla sit amet. Ut euismod, elit id dapibus aliquam, ipsum enim interdum nibh, eu blandit orci velit vel urna. Nullam dignissim sem eu purus cursus, eget lacinia quam hendrerit. Morbi dictum sollicitudin mauris, non tristique neque auctor ac. </p>
</div>

<div class="row">
  <h1>Pages#about</h1>
  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce a lacus vitae lacus ornare sollicitudin a ut turpis. Nam id diam ut velit hendrerit vestibulum rhoncus vitae risus. Suspendisse feugiat mollis velit, non molestie sem viverra sed. Sed at ipsum at felis porttitor consequat eget at arcu. Duis bibendum nunc nec elit condimentum, a tincidunt nulla viverra. Maecenas eget nulla at massa faucibus accumsan. Duis pretium ipsum vel volutpat facilisis. Duis ornare pharetra orci et ullamcorper. Suspendisse lacinia augue dolor, eu rutrum ante fringilla sit amet. Ut euismod, elit id dapibus aliquam, ipsum enim interdum nibh, eu blandit orci velit vel urna. Nullam dignissim sem eu purus cursus, eget lacinia quam hendrerit. Morbi dictum sollicitudin mauris, non tristique neque auctor ac. </p>
</div>

<div class="row">
  <h1>Pages#about</h1>
  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce a lacus vitae lacus ornare sollicitudin a ut turpis. Nam id diam ut velit hendrerit vestibulum rhoncus vitae risus. Suspendisse feugiat mollis velit, non molestie sem viverra sed. Sed at ipsum at felis porttitor consequat eget at arcu. Duis bibendum nunc nec elit condimentum, a tincidunt nulla viverra. Maecenas eget nulla at massa faucibus accumsan. Duis pretium ipsum vel volutpat facilisis. Duis ornare pharetra orci et ullamcorper. Suspendisse lacinia augue dolor, eu rutrum ante fringilla sit amet. Ut euismod, elit id dapibus aliquam, ipsum enim interdum nibh, eu blandit orci velit vel urna. Nullam dignissim sem eu purus cursus, eget lacinia quam hendrerit. Morbi dictum sollicitudin mauris, non tristique neque auctor ac. </p>
</div>

app/views/pages/home.html.erb
<div class="row">
  <h1>Pages#home</h1>

  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce a lacus vitae lacus ornare sollicitudin a ut turpis. Nam id diam ut velit hendrerit vestibulum rhoncus vitae risus. Suspendisse feugiat mollis velit, non molestie sem viverra sed. Sed at ipsum at felis porttitor consequat eget at arcu. Duis bibendum nunc nec elit condimentum, a tincidunt nulla viverra. Maecenas eget nulla at massa faucibus accumsan. Duis pretium ipsum vel volutpat facilisis. Duis ornare pharetra orci et ullamcorper. Suspendisse lacinia augue dolor, eu rutrum ante fringilla sit amet. Ut euismod, elit id dapibus aliquam, ipsum enim interdum nibh, eu blandit orci velit vel urna. Nullam dignissim sem eu purus cursus, eget lacinia quam hendrerit. Morbi dictum sollicitudin mauris, non tristique neque auctor ac. </p>
</div>

<div class="row">
  <h1>Pages#home</h1>
  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce a lacus vitae lacus ornare sollicitudin a ut turpis. Nam id diam ut velit hendrerit vestibulum rhoncus vitae risus. Suspendisse feugiat mollis velit, non molestie sem viverra sed. Sed at ipsum at felis porttitor consequat eget at arcu. Duis bibendum nunc nec elit condimentum, a tincidunt nulla viverra. Maecenas eget nulla at massa faucibus accumsan. Duis pretium ipsum vel volutpat facilisis. Duis ornare pharetra orci et ullamcorper. Suspendisse lacinia augue dolor, eu rutrum ante fringilla sit amet. Ut euismod, elit id dapibus aliquam, ipsum enim interdum nibh, eu blandit orci velit vel urna. Nullam dignissim sem eu purus cursus, eget lacinia quam hendrerit. Morbi dictum sollicitudin mauris, non tristique neque auctor ac. </p>
</div>

<div class="row">
  <h1>Pages#home</h1>
  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce a lacus vitae lacus ornare sollicitudin a ut turpis. Nam id diam ut velit hendrerit vestibulum rhoncus vitae risus. Suspendisse feugiat mollis velit, non molestie sem viverra sed. Sed at ipsum at felis porttitor consequat eget at arcu. Duis bibendum nunc nec elit condimentum, a tincidunt nulla viverra. Maecenas eget nulla at massa faucibus accumsan. Duis pretium ipsum vel volutpat facilisis. Duis ornare pharetra orci et ullamcorper. Suspendisse lacinia augue dolor, eu rutrum ante fringilla sit amet. Ut euismod, elit id dapibus aliquam, ipsum enim interdum nibh, eu blandit orci velit vel urna. Nullam dignissim sem eu purus cursus, eget lacinia quam hendrerit. Morbi dictum sollicitudin mauris, non tristique neque auctor ac. </p>
</div>

app/views/pages/products.html.erb
<h1>Pages#products</h1>
<p>Find me in app/views/pages/products.html.erb</p>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product, class:"btn btn-primary" %> |
<%= link_to 'Back', products_path, class:"btn btn-primary" %>

app/views/products/index.html.erb
<table class="table">
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table class="table">
  <thead>
    <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.price %></td>
        <td><%= link_to 'Show', product, class:"btn btn-primary"%></td>
        <td><%= link_to 'Edit', edit_product_path(product), class:"btn btn-primary"%></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-primary"%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path, class:"btn btn-primary" %>
</div>
</table>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path, class:"btn btn-primary" %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<%= link_to 'Edit', edit_product_path(@product), class:"btn btn-primary" %> |
<%= link_to 'Back', products_path , class:"btn btn-primary"%>